spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  logging:
    file:
      name: log-pro.log
      classpath: log/log-pro.log
    level:
      com.blog: info
  rsocket:
    server:
      port: 8081
