spring:
    thymeleaf:
        mode: HTML5
        check-template-location: true
        check-template: true
        suffix: .html
        encoding: UTF-8
        cache: false
    profiles:
        active: dev
    servlet:
      multipart:
        enabled: true #允许上传文件
        max-file-size: 200MB
        max-request-size: 200MB


